'use client'
import { FormEvent, useState } from 'react'
import { ConfirmActionDialog } from '@/components/admin/confirm-action-dialog'
import { toast } from '@/hooks/use-toast'
import { ProjectEditor, emptyProjectForm, projectToForm, type ProjectForm } from './project-editor'
import { ProjectList } from './project-list'
export type AdminProject = { id:string; title:string; description:string; longDescription:string|null; githubUrl:string|null; liveUrl:string|null; tags:string; contentType:'portfolio'|'discover'; featured:boolean; published:boolean; order:number }
export function ProjectsManager({ initialProjects }:{initialProjects:AdminProject[]}) {
 const [projects,setProjects]=useState(initialProjects); const [form,setForm]=useState<ProjectForm>(emptyProjectForm); const [saving,setSaving]=useState(false); const [deleteTarget,setDeleteTarget]=useState<AdminProject|null>(null); const [deleting,setDeleting]=useState(false)
 const updateForm=<K extends keyof ProjectForm>(key:K,value:ProjectForm[K])=>setForm(c=>({...c,[key]:value}))
 async function saveProject(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);try{const response=await fetch('/api/admin/projects',{method:form.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await response.json() as {project?:AdminProject;error?:string};const savedProject=data.project;if(!response.ok||!savedProject)throw new Error(data.error||'Failed to save project');setProjects(c=>form.id?c.map(p=>p.id===savedProject.id?savedProject:p):[savedProject,...c]);setForm(emptyProjectForm);toast({title:'Project saved',description:'The portfolio project was saved successfully.'})}catch(error){toast({title:'Save failed',description:error instanceof Error?error.message:'The project was not saved.',variant:'destructive'})}finally{setSaving(false)}}
 async function deleteProject(){if(!deleteTarget)return;setDeleting(true);try{const response=await fetch(`/api/admin/projects?id=${encodeURIComponent(deleteTarget.id)}`,{method:'DELETE'});if(!response.ok)throw new Error('The project was not deleted.');setProjects(c=>c.filter(p=>p.id!==deleteTarget.id));if(form.id===deleteTarget.id)setForm(emptyProjectForm);setDeleteTarget(null);toast({title:'Project deleted',description:'The portfolio project was permanently deleted.'})}catch(error){toast({title:'Delete failed',description:error instanceof Error?error.message:'The project was not deleted.',variant:'destructive'})}finally{setDeleting(false)}}
 return <div className="space-y-6"><ProjectEditor form={form} saving={saving} onChange={updateForm} onSubmit={saveProject} onCancel={()=>setForm(emptyProjectForm)}/><ProjectList projects={projects} onEdit={p=>setForm(projectToForm(p))} onDelete={setDeleteTarget}/><ConfirmActionDialog open={Boolean(deleteTarget)} title={`Delete ${deleteTarget?.title??'project'}?`} description="This permanently removes the project and cannot be undone." pending={deleting} onCancel={()=>setDeleteTarget(null)} onConfirm={()=>void deleteProject()}/></div>
}
