import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('production database migration safety', () => {
  it('backs up persistent SQLite state and verifies structural baseline state before migration', () => {
    const deploy = readFileSync(resolve(process.cwd(), 'ops/deploy/deploy.sh'), 'utf8')
    const planner = readFileSync(resolve(process.cwd(), 'scripts/deploy/prisma-baseline-state.mjs'), 'utf8')

    const buildIndex = deploy.indexOf('pnpm run build')
    const baselineStateIndex = deploy.indexOf('node scripts/deploy/prisma-baseline-state.mjs')
    const legacyPlanIndex = deploy.indexOf('node scripts/deploy/prisma-baseline-state.mjs --legacy-resolve-plan')
    const preflightStatusIndex = deploy.indexOf('pnpm exec prisma migrate status 2>&1')
    const migrationIndex = deploy.indexOf('pnpm exec prisma migrate deploy', preflightStatusIndex)
    const postMigrationStatusIndex = deploy.indexOf('if ! pnpm exec prisma migrate status; then', migrationIndex)
    const driftIndex = deploy.indexOf('pnpm exec prisma migrate diff --from-url "$DATABASE_URL" --to-schema-datamodel prisma/schema.prisma --exit-code', postMigrationStatusIndex)
    const replaceAppIndex = deploy.indexOf('pm2 delete "$APP_NAME"', driftIndex)
    const publishLinkIndex = deploy.indexOf('ln -sfn "$RELEASE_DIR" "$CURRENT_LINK"', replaceAppIndex)

    expect(planner).toContain('20260617000000_baseline_legacy_portfolio')
    expect(planner).toContain('20260618141730_add_analytics_funnel_tracking')
    expect(deploy).toContain('Following migrations have not yet been applied')
    expect(deploy).toContain('legacy-needs-baseline')
    expect(deploy).toContain('ASDEV_BUILD_SKIP_DYNAMIC_DB=1 pnpm run build')
    expect(deploy).toContain('DATABASE_URL must use an absolute SQLite file URL')
    expect(deploy).toContain('DB_PATH="${DATABASE_URL#file:}"')
    expect(deploy).toContain('BACKUP_DIR="$BASE_DIR/shared/backups/$ENVIRONMENT"')
    expect(deploy).toContain('PREVIOUS_RELEASE="$(readlink -f "$CURRENT_LINK" 2>/dev/null || true)"')
    expect(deploy).toContain('pm2 stop "$APP_NAME"')
    expect(deploy).toContain('snapshot_database')
    expect(deploy).toContain('restore_database_snapshot')
    expect(deploy).toContain('rollback_previous_release')
    expect(deploy).toContain('pm2 restart "$APP_NAME" --update-env')
    expect(buildIndex).toBeGreaterThan(-1)
    expect(baselineStateIndex).toBeGreaterThan(buildIndex)
    expect(legacyPlanIndex).toBeGreaterThan(baselineStateIndex)
    expect(preflightStatusIndex).toBeGreaterThan(legacyPlanIndex)
    expect(migrationIndex).toBeGreaterThan(preflightStatusIndex)
    expect(postMigrationStatusIndex).toBeGreaterThan(migrationIndex)
    expect(driftIndex).toBeGreaterThan(postMigrationStatusIndex)
    expect(replaceAppIndex).toBeGreaterThan(driftIndex)
    expect(publishLinkIndex).toBeGreaterThan(replaceAppIndex)
  })

  it('resolves only structurally verified legacy effects and restores the snapshot if any resolution fails', () => {
    const deploy = readFileSync(resolve(process.cwd(), 'ops/deploy/deploy.sh'), 'utf8')

    expect(deploy).toContain('mapfile -t LEGACY_RESOLVE_MIGRATIONS')
    expect(deploy).toContain('for LEGACY_MIGRATION in "${LEGACY_RESOLVE_MIGRATIONS[@]}"; do')
    expect(deploy).toContain('pnpm exec prisma migrate resolve --applied "$LEGACY_MIGRATION"')
    expect(deploy).toContain('legacy migration resolution failed; restoring pre-migration snapshot')
  })

  it('restores service availability and database state when migration preflight, legacy resolution, or schema drift fails', () => {
    const deploy = readFileSync(resolve(process.cwd(), 'ops/deploy/deploy.sh'), 'utf8')

    const structuralFailureIndex = deploy.indexOf('Prisma baseline state inspection failed; refusing rollout')
    const structuralRestartIndex = deploy.indexOf('restart_previous_app || true', structuralFailureIndex)
    const structuralExitIndex = deploy.indexOf('exit 1', structuralFailureIndex)
    const preflightFailureIndex = deploy.indexOf('Prisma migration preflight failed; refusing rollout')
    const preflightRestoreIndex = deploy.indexOf('restore_database_snapshot', preflightFailureIndex)
    const preflightRestartIndex = deploy.indexOf('restart_previous_app || true', preflightFailureIndex)
    const preflightExitIndex = deploy.indexOf('exit 1', preflightFailureIndex)
    const resolutionFailureIndex = deploy.indexOf('legacy migration resolution failed; restoring pre-migration snapshot')
    const resolutionRestoreIndex = deploy.indexOf('restore_database_snapshot', resolutionFailureIndex)
    const resolutionRestartIndex = deploy.indexOf('restart_previous_app || true', resolutionFailureIndex)
    const resolutionExitIndex = deploy.indexOf('exit 1', resolutionFailureIndex)
    const driftFailureIndex = deploy.indexOf('database schema drift detected after migration; restoring pre-migration snapshot')
    const driftRestoreIndex = deploy.indexOf('restore_database_snapshot', driftFailureIndex)
    const driftRestartIndex = deploy.indexOf('restart_previous_app || true', driftFailureIndex)
    const driftExitIndex = deploy.indexOf('exit 1', driftFailureIndex)

    expect(structuralFailureIndex).toBeGreaterThan(-1)
    expect(structuralRestartIndex).toBeGreaterThan(structuralFailureIndex)
    expect(structuralExitIndex).toBeGreaterThan(structuralRestartIndex)
    expect(preflightFailureIndex).toBeGreaterThan(-1)
    expect(preflightRestoreIndex).toBeGreaterThan(preflightFailureIndex)
    expect(preflightRestartIndex).toBeGreaterThan(preflightRestoreIndex)
    expect(preflightExitIndex).toBeGreaterThan(preflightRestartIndex)
    expect(resolutionFailureIndex).toBeGreaterThan(-1)
    expect(resolutionRestoreIndex).toBeGreaterThan(resolutionFailureIndex)
    expect(resolutionRestartIndex).toBeGreaterThan(resolutionRestoreIndex)
    expect(resolutionExitIndex).toBeGreaterThan(resolutionRestartIndex)
    expect(driftFailureIndex).toBeGreaterThan(-1)
    expect(driftRestoreIndex).toBeGreaterThan(driftFailureIndex)
    expect(driftRestartIndex).toBeGreaterThan(driftRestoreIndex)
    expect(driftExitIndex).toBeGreaterThan(driftRestartIndex)
  })

  it('restores the database snapshot before starting the previous release after post-migration app failure', () => {
    const deploy = readFileSync(resolve(process.cwd(), 'ops/deploy/deploy.sh'), 'utf8')

    const rollbackStart = deploy.indexOf('rollback_previous_release() {')
    const rollbackEnd = deploy.indexOf('\n}\n\n# Quiesce', rollbackStart)
    const rollbackBody = deploy.slice(rollbackStart, rollbackEnd)
    const stopNewAppIndex = rollbackBody.indexOf('pm2 delete "$APP_NAME"')
    const restoreIndex = rollbackBody.indexOf('restore_database_snapshot')
    const startPreviousIndex = rollbackBody.indexOf('pm2 start ecosystem.config.cjs --only "$APP_NAME" --update-env')

    expect(rollbackStart).toBeGreaterThan(-1)
    expect(stopNewAppIndex).toBeGreaterThan(-1)
    expect(restoreIndex).toBeGreaterThan(stopNewAppIndex)
    expect(startPreviousIndex).toBeGreaterThan(restoreIndex)
    expect(rollbackBody).toContain('CRITICAL: database snapshot restore failed during release rollback')

    const startFailureIndex = deploy.indexOf('new application failed to start; rolling back previous release')
    const startFailureRollbackIndex = deploy.indexOf('rollback_previous_release || true', startFailureIndex)
    const healthFailureIndex = deploy.indexOf('health check failed after 20 attempts; rolling back previous release')
    const healthFailureRollbackIndex = deploy.indexOf('rollback_previous_release || true', healthFailureIndex)

    expect(startFailureIndex).toBeGreaterThan(-1)
    expect(startFailureRollbackIndex).toBeGreaterThan(startFailureIndex)
    expect(healthFailureIndex).toBeGreaterThan(-1)
    expect(healthFailureRollbackIndex).toBeGreaterThan(healthFailureIndex)
  })

  it('recreates deterministic rollback metadata for legacy running releases', () => {
    const deploy = readFileSync(resolve(process.cwd(), 'ops/deploy/deploy.sh'), 'utf8')

    expect(deploy).toContain('Older governed releases may predate ecosystem metadata')
    expect(deploy).toContain('cwd: \'$PREVIOUS_RELEASE\'')
    expect(deploy).toContain("args: '.next/standalone/server.js'")
    expect(deploy).toContain('chmod 600 "$PREVIOUS_RELEASE/ecosystem.config.cjs"')
  })
})
