-- Baseline marker for the pre-Prisma-migrations portfolio SQLite schema.
--
-- The actual first replayable schema snapshot is the historical
-- 20260618141730_add_analytics_funnel_tracking migration. Production databases
-- that predate Prisma migration metadata resolve this marker (and the malformed
-- overlapping snapshot) only after structural verification in deploy tooling.
-- Keeping this migration as a no-op marker prevents fresh databases from
-- creating the legacy core tables twice.
