#!/usr/bin/env bash
set -euo pipefail

ENVIRONMENT=""
BASE_DIR="/var/www/my-portfolio"
APP_SLUG="my-portfolio"
REQUESTED_RELEASE_ID=""

usage() {
  cat <<USAGE
Usage: $(basename "$0") --env <staging|production> --release-id <id> [options]

Required:
  --env <name>             Target environment (staging, production)
  --release-id <id>        Exact release identifier to roll back

Optional:
  --app-slug <name>        Logical app slug (default: my-portfolio)
  --base-dir <path>        Base directory on server (default: /var/www/my-portfolio)
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)
      ENVIRONMENT="${2:-}"
      shift 2
      ;;
    --release-id)
      REQUESTED_RELEASE_ID="${2:-}"
      shift 2
      ;;
    --base-dir)
      BASE_DIR="${2:-}"
      shift 2
      ;;
    --app-slug)
      APP_SLUG="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[rollback] unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$ENVIRONMENT" || -z "$REQUESTED_RELEASE_ID" ]]; then
  usage
  exit 1
fi
if [[ "$ENVIRONMENT" != "staging" && "$ENVIRONMENT" != "production" ]]; then
  echo "[rollback] unsupported environment: $ENVIRONMENT" >&2
  exit 1
fi
if [[ ! "$REQUESTED_RELEASE_ID" =~ ^[A-Za-z0-9._-]+$ ]]; then
  echo "[rollback] invalid release id" >&2
  exit 1
fi

STATE_FILE="$BASE_DIR/shared/deploy-state/$ENVIRONMENT/$REQUESTED_RELEASE_ID.env"
if [[ ! -f "$STATE_FILE" ]]; then
  echo "[rollback] exact release state not found: $STATE_FILE" >&2
  exit 1
fi

# State files are generated by deploy.sh with mode 0600 and shell-escaped values.
# shellcheck disable=SC1090
source "$STATE_FILE"

required=(RELEASE_ID RELEASE_DIR PREVIOUS_RELEASE APP_WAS_RUNNING SNAPSHOT_DIR DB_PATH APP_NAME CURRENT_LINK ENV_FILE PORT)
for name in "${required[@]}"; do
  if [[ -z "${!name+x}" ]]; then
    echo "[rollback] incomplete state file: missing $name" >&2
    exit 1
  fi
done

if [[ "$RELEASE_ID" != "$REQUESTED_RELEASE_ID" ]]; then
  echo "[rollback] release state mismatch" >&2
  exit 1
fi
EXPECTED_APP_NAME="$APP_SLUG-$ENVIRONMENT"
if [[ "$APP_NAME" != "$EXPECTED_APP_NAME" ]]; then
  echo "[rollback] app name mismatch in release state" >&2
  exit 1
fi
for path in "$RELEASE_DIR" "$SNAPSHOT_DIR" "$DB_PATH" "$CURRENT_LINK" "$ENV_FILE"; do
  if [[ "$path" != "$BASE_DIR/"* ]]; then
    echo "[rollback] unsafe path outside base directory: $path" >&2
    exit 1
  fi
done
if [[ -n "$PREVIOUS_RELEASE" && "$PREVIOUS_RELEASE" != "$BASE_DIR/"* ]]; then
  echo "[rollback] unsafe previous release path" >&2
  exit 1
fi

restore_database_snapshot() {
  rm -f -- "$DB_PATH" "${DB_PATH}-wal" "${DB_PATH}-shm" "${DB_PATH}-journal" || return 1

  if [[ -f "$SNAPSHOT_DIR/.database-absent" ]]; then
    return 0
  fi
  if [[ ! -f "$SNAPSHOT_DIR/database.sqlite" ]]; then
    echo "[rollback] database snapshot is incomplete" >&2
    return 1
  fi

  cp -a -- "$SNAPSHOT_DIR/database.sqlite" "$DB_PATH" || return 1
  for suffix in -wal -shm -journal; do
    if [[ -f "$SNAPSHOT_DIR/database.sqlite${suffix}" ]]; then
      cp -a -- "$SNAPSHOT_DIR/database.sqlite${suffix}" "${DB_PATH}${suffix}" || return 1
    fi
  done
}

# The replacement process must not be using SQLite while bytes/WAL are restored.
pm2 delete "$APP_NAME" >/dev/null 2>&1 || true

if ! restore_database_snapshot; then
  echo "[rollback] CRITICAL: database snapshot restore failed; refusing previous app startup" >&2
  exit 1
fi

echo "[rollback] database snapshot restored for failed release $RELEASE_ID"

if [[ "$APP_WAS_RUNNING" != "true" ]]; then
  if [[ "$(readlink -f "$CURRENT_LINK" 2>/dev/null || true)" == "$RELEASE_DIR" ]]; then
    rm -f -- "$CURRENT_LINK"
  fi
  echo "[rollback] no previous application was running; database-only rollback completed"
  exit 0
fi

if [[ -z "$PREVIOUS_RELEASE" || ! -f "$PREVIOUS_RELEASE/ecosystem.config.cjs" ]]; then
  echo "[rollback] previous release metadata unavailable after database restore" >&2
  exit 1
fi

(
  cd "$PREVIOUS_RELEASE"
  pm2 start ecosystem.config.cjs --only "$APP_NAME" --update-env
) || {
  echo "[rollback] previous application failed to start" >&2
  exit 1
}
pm2 save >/dev/null 2>&1 || true

HEALTHY=false
for attempt in {1..20}; do
  if curl -fsS "http://127.0.0.1:$PORT/api/ready" >/dev/null 2>&1; then
    HEALTHY=true
    break
  fi
  sleep 2
done
if [[ "$HEALTHY" != "true" ]]; then
  echo "[rollback] previous release failed /api/ready after database restore" >&2
  exit 1
fi

# Only publish the old release pointer after the restored app is healthy.
ln -sfn "$PREVIOUS_RELEASE" "$CURRENT_LINK"
echo "[rollback] completed exact release rollback for $RELEASE_ID -> $PREVIOUS_RELEASE"
