'use client'

import { useEffect, useState } from 'react'
import { AdminPageHeader } from '@/components/admin/admin-page-header'
import { Button } from '@/components/ui/button'

type Post = { id: string; title: string; slug: string; excerpt: string; content: string; tags: string; category: string; published: boolean }

export default function AdminBlogPage() {
  const [posts, setPosts] = useState<Post[]>([]); const [editing, setEditing] = useState<string | null>(null); const [preview, setPreview] = useState(false); const [title, setTitle] = useState(''); const [slug, setSlug] = useState(''); const [excerpt, setExcerpt] = useState(''); const [content, setContent] = useState(''); const [error, setError] = useState('')
  const load = async () => { const response = await fetch('/api/admin/blog?published=all', { cache: 'no-store' }); if (response.ok) setPosts((await response.json()).posts as Post[]) }
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [])
  const reset = () => { setEditing(null); setTitle(''); setSlug(''); setExcerpt(''); setContent(''); setPreview(false) }
  const save = async (published = false) => { setError(''); const payload = { title, slug, excerpt, content, tags: [], category: 'engineering', published, featured: false }; const response = await fetch('/api/admin/blog' + (editing ? '' : ''), { method: editing ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(editing ? { ...payload, id: editing } : payload) }); if (!response.ok) { setError('Unable to save post'); return }; reset(); await load() }
  const edit = (post: Post) => { setEditing(post.id); setTitle(post.title); setSlug(post.slug); setExcerpt(post.excerpt); setContent(post.content); setPreview(false) }
  const togglePublish = async (post: Post) => { const response = await fetch('/api/admin/blog', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: post.id, published: !post.published }) }); if (!response.ok) { setError('Unable to update publication state'); return }; await load() }
  const remove = async (id: string) => { if (!window.confirm('Delete this post?')) return; const response = await fetch(`/api/admin/blog?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); if (!response.ok) setError('Unable to delete post'); await load() }
  return <div className="space-y-8"><AdminPageHeader title="Blog" description="Draft, review and publish engineering insights." /><section className="space-y-4 rounded-xl border p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{editing ? 'Edit post' : 'New draft'}</h2><Button variant="outline" size="sm" onClick={() => setPreview((value) => !value)}>{preview ? 'Edit markdown' : 'Preview'}</Button></div>{preview ? <article className="prose max-w-none whitespace-pre-wrap">{content || 'Nothing to preview yet.'}</article> : <><input aria-label="Title" className="h-11 w-full rounded border px-3" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Title" /><input aria-label="Slug" className="h-11 w-full rounded border px-3" value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="slug" /><textarea aria-label="Excerpt" className="min-h-20 w-full rounded border p-3" value={excerpt} onChange={(e) => setExcerpt(e.target.value)} placeholder="Excerpt" /><textarea aria-label="Content" className="min-h-40 w-full rounded border p-3" value={content} onChange={(e) => setContent(e.target.value)} placeholder="Markdown content" /></>}<div className="flex gap-2"><Button onClick={() => void save(false)}>{editing ? 'Save draft' : 'Save draft'}</Button><Button variant="secondary" onClick={() => void save(true)}>Publish</Button>{editing ? <Button variant="ghost" onClick={reset}>Cancel</Button> : null}</div>{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}</section><section className="space-y-3"><h2 className="text-lg font-semibold">Library</h2>{posts.map((post) => <article key={post.id} className="flex items-center justify-between rounded border p-4"><div><h3 className="font-medium">{post.title}</h3><p className="text-sm text-muted-foreground">{post.published ? 'Published' : 'Draft'} · {post.slug}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => edit(post)}>Edit</Button><Button variant="secondary" size="sm" onClick={() => void togglePublish(post)}>{post.published ? 'Unpublish' : 'Publish'}</Button><Button variant="destructive" size="sm" onClick={() => void remove(post.id)}>Delete</Button></div></article>)}</section></div>
}
